jobs:
  build:
    docker:
      - image: circleci/node:dubnium

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install packages
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run eslint
          command: yarn lint

      - run:
          name: Run tests
          command: yarn test --maxWorkers=2 --coverage

  release:
    docker:
      - image: circleci/node:dubnium

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: release
          command: npm run semantic-release || true

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
